blank_issues_enabled: false
contact_links:
  - name: Questions and discussion
    url: https://github.com/maxonamission/obsidian-parallax/discussions
    about: For open-ended questions or discussion instead of a bug or feedback report
